version: "3"
services:
  feecc_analytics:
    build:
      dockerfile: Dockerfile
    env_file:
        - .env
    ports:
      - "5002:8000"
    volumes:
      - "./output:/output"
      - "/dev/usb:/dev/usb"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"