version: "3"
services:
  feecc_analytics:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
        - .env
    ports:
      - "5002:8000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
