name: Deploy in DO Container Registry (development)
on:
  push:
    branches: [ development ]
    
jobs:
  Build-and-push-DockerCont:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login in Container Registry Digital Ocean
        run: doctl registry login

      - name: Build Docker Container
        run: docker build ./ -t ${{ secrets.DOREGISTRY }}/feecc-analytics-backend:dev
      
      - name: Tag container for Container Registry Digital Ocean
        run: docker tag ${{ secrets.DOREGISTRY }}/feecc-analytics-backend:dev ${{ secrets.DOREGISTRY }}/feecc-analytics-backend

      - name: Push container in Container Registry Digital Ocean
        run: docker push ${{ secrets.DOREGISTRY }}/feecc-analytics-backend:dev
